import json

not_synonym = {
    'làm': ['đánh'],
    'đất': ['ghét'],
    'ra': ['vào'],
    'vào': ['ra'],
    'chủ tịch': ['chủ toạ'],
    'vừng': ['vầng'],
    'tròn': ['trọn'],
    'giống': ['chi', 'hệt'],
    'nhẹ': ['nặng'],
    'nặng': ['nhẹ'],
    'lân': ['lạm', 'lấn'],
    'được': ['thắng', 'nổi', 'đặng'],
    'giai đoạn': ['tuổi'],
    'nước': ['nác'],
    'thứ': ['ngữ'],
    'đỏ': ['hồng'],
    'tốt': ['đặng', 'được'],
    'họ': ['gia tộc'],
    'tuần': ['kì'],
    'kì': ['tuần'],
    'tỉa': ['trỉa'],
    'lúc': ['chốc', 'lát', 'buổi', 'chập'],
    'hoa': ['huê'],
    'cắt': ['ngắt', 'bốc', 'cân'],
    'thước': ['tất'],
    'điều': ['đào lộn hột'],
    'cánh': ['bè', 'phái', 'phe'],
    'ươm': ['ương'],
    'sản xuất': ['sinh sản'],
    'vốn': ['vốn dĩ', 'nguyên'],
    'dài': ['trường'],
    'sạch': ['ráo', 'tiệt', 'nhẵn'],
    'xong': ['đoản', 'đoạn'],
    'đốt': ['cắn'],
    'dại': ['ngộ'],
    'trung bình': ['làng nhàng', 'nhàng nhàng'],
    'nóng': ['lạnh'],
    'lạnh': ['rét'],
    'thấy': ['chộ'],
    'chứa': ['chứa chấp'],
    'điều kiện': ['hoàn cảnh'],
    'non': ['đuôi', 'mát'],
    'thối': ['thoái'],
    'ta': ['mỗ'],
    'còn': ['đang'],
    'để': ['đặng'],
    'đảo': ['cù lao'],
    'này': ['ni'],
    'nó': ['y', 'nghỉ'],
    'khô': ['khô khan'],
    'đưa': ['tiễn'],
    'lót': ['lát', 'tã'],
    'chết': ['tắt thở'],
    'thước': ['tất'],
    'kích thước': ['kích tấc'],
    'nhiều': ['ối', 'giàu'],
    'ép': ['nép', 'bứt', 'buộc', 'bắt'],
    'tròn': ['trọn.#'],
    'sai': ['sây'],
    'đen': ['xui', 'rủi', 'mun'],
    'hạn': ['vận hạn'],
    'chủ yếu': ['cốt tử'],
    'tàn dư': ['tàn tích'],
    'biện pháp': ['thủ pháp'],
    'xì': ['phì', 'xùy', 'hỉ'],
    'tên': ['thằng', 'gã'],
    'chi phí': ['phí tổn'],
    'chi': ['giống', 'gì'],
    'thành phố': ['tỉnh thành'],
    'báo cáo': ['thưa', 'bẩm'],
    'dịch': ['xê', 'xịch', 'nhích', 'xích'],
    'đàn': ['cầm', 'bọn', 'lũ'],
    'thuộc': ['thuộc lòng', 'thuộc làu'],
    'ăn': ['xực', 'ngốn', 'tọng', 'măm', 'hốc'],
    'mức': ['ngữ'],
    'khu': ['đít'],
    'mực': ['mực tàu'],
    'nạn': ['nàn', 'tệ'],
    'lao động': ['cần lao'],
    'số': ['số mệnh', 'số phận'],
    'cụm': ['khóm'],
    'ven': ['vệ'],
    'hải sản': ['thủy sản'],
    'thủy sản': ['hải sản'],
    'đóng': ['tắt'],
    'xã hội': ['tầng lớp'],
    'tầng lớp': ['xã hội', 'từng lớp'],
    'hợp đồng': ['giao kèo'],
    'thực tế': ['thực tại'],
    'bơm': ['thổi phồng'],
    'liên quan': ['liên can', 'can hệ'],
    'qua': ['trải qua'],
    'biển': ['bể'],
    'bể': ['biển'],
    'tiền': ['đồng cân'],
    'khai thác': ['khai khẩn'],
    'chiến sĩ': ['đội viên'],
    'đầy': ['chật'],
    'giao thông': ['liên lạc'],
    'liên lạc': ['giao thông'],
    'tập trung': ['tập kết'],
    'thực hiện': ['thực hành'],
    'đẩy': ['ẩn', 'ẩy', 'đẩn'],
    'kiểm tra': ['soát'],
    'phát sinh': ['nảy'],
    'học sinh': ['học trò'],
    'tiết kiệm': ['kiệm ước', 'tùng tiệm'],
    'kể': ['thuật'],
    'môn': ['món', 'khoa'],
    'món': ['môn'],
    'khoa': ['môn'],
    'đi': ['phai', 'đạn', 'về'],
    'về': ['đi'],
    'bảo tồn': ['bảo tàng'],
    'bảo tàng': ['bảo tồn'],
    'độ': ['quãng'],
    'tuổi': ['giai đoạn'],
    'mua': ['chuốc'],
    'tất cả': ['tất', 'tất tật', 'tất thảy'],
    'lễ': ['lỡi'],
    'gì': ['chi'],
    'gọi': ['đòi'],
    'khám': ['khám xét'],
    'chiều': ['bề'],
    'bề': ['chiều'],
    'trở thành': ['trở nên'],
    'trở nên': ['trở thành'],
    'tích cực': ['hăng hái'],
    'sinh': ['đâm', 'đổ', 'hóa'],
    'thường xuyên': ['luôn luôn'],
    'lớp': ['lóng', 'dạo', 'cữ'],
    'họp': ['hội'],
    'hội': ['họp'],
    'đỉnh': ['trốc', 'mỏm'],
    'vẽ': ['vẽ vời', 'bày vẽ', 'vẽ chuyện'],
    'đảng': ['phái', 'bè', 'phe'],
    'mục tiêu': ['đích'],
    'bò': ['bơ'],
    'bơ': ['bò'],
    'mặt': ['phương diện', 'bình diện'],
    'chúng ta': ['chúng mình'],
    'thường trực': ['trực'],
    'thưa': ['báo cáo', 'trình'],
    'tinh thần': ['ý thức']
}

vi_words = json.load(open('./data_syn.json', mode='r'))

for word in not_synonym:
    synonym = vi_words.get(word, {}).get('syn', {})
    for not_syn in not_synonym[word]:
        for syn_type in ['V', 'N', 'A']:
            syn_list = synonym.get(syn_type, None)
            if syn_list is not None and not_syn in syn_list:
                syn_list.remove(not_syn)
                if len(syn_list) != 0:
                    vi_words[word]['syn'][syn_type] = syn_list
                else:
                    del vi_words[word]['syn'][syn_type]

with open('./data_syn_processed.json', mode='w+', encoding='utf-8') as f:
    json.dump(vi_words, f, ensure_ascii=False)